name: ebay_api_config

# Trading API Sandbox - https://www.x.com/developers/ebay/products/trading-api
api.sandbox.ebay.com:
    compatability: 719
    appid: app_id
    certid: certid
    devid: devid
    token: token

# Trading API - https://www.x.com/developers/ebay/products/trading-api
# To-do! 
api.ebay.com:
    compatability: 719
    appid: appid
    certid: certid
    devid: devid
    token: token

# Finding API - https://developer.ebay.com/devzone/finding/Concepts/FindingAPIGuide.html?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5336728181&customid=&toolid=10001 
svcs.ebay.com:
    appid: appid

# Shopping API - https://www.x.com/developers/ebay/products/shopping-api
open.api.ebay.com:
    appid: appid
